const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DATA_DIR=process.env.DATA_DIR||ROOT,DB_FILE=path.join(DATA_DIR,'db.json');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const rooms=new Map(),botGames=new Map(),sessions=new Map(),adminSessions=new Map(),rateBuckets=new Map();
const PLAYER_TIMEOUT=Number(process.env.PLAYER_TIMEOUT_MS||5000),DISCONNECT_GRACE=Number(process.env.DISCONNECT_GRACE_MS||55*1000),ROOM_TTL=60*60*1000,SESSION_TTL=3650*24*60*60*1000,ADMIN_SESSION_TTL=8*60*60*1000,MAX_STAKE=1000000000,MAX_BODY=1e6;
const RATE_WINDOW=60000;
const DAILY_GIFT_AMOUNTS=[1000,2000,3000,4000,5000,6000,10000];
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;
const STORE_BOARDS=[['classic','Классика','Дерево и латунь',0],['emerald','Emerald','Изумрудный камень',30000],['midnight','Midnight','Ночной обсидиан',45000],['royal','Royal','Королевское золото',60000],['ice','Ice','Ледяной кристалл',75000],['vip_jewel','💎 Ювелирная VIP','Эксклюзивная ювелирная доска',null,'vip']];
const STORE_PIECES=[['classic','Classic','Классические шашки',0],['neo','Neo','Современный минимализм',25000],['royal','Royal','Премиальные золотые',45000],['glass','Glass','Стеклянные фигуры',65000],['neon','Neon','Неоновый стиль',80000],['vip_gem','💎 Ювелирные VIP','Эксклюзивные ювелирные фигуры',null,'vip']];
function uid(){return crypto.randomBytes(16).toString('hex')} function now(){return Date.now()}
function json(res,code,data){const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; media-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'X-Frame-Options':'DENY','Permissions-Policy':'camera=(),microphone=(),geolocation=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin'};if(res.getHeader('Set-Cookie'))h['Set-Cookie']=res.getHeader('Set-Cookie');if(process.env.NODE_ENV==='production')h['Strict-Transport-Security']='max-age=31536000; includeSubDomains';res.writeHead(code,h);res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let b='',done=false;const fail=e=>{if(done)return;done=true;reject(e)};req.on('data',c=>{if(done)return;b+=c;if(b.length>MAX_BODY){fail(new Error('Слишком большой запрос'));req.destroy()}});req.on('end',()=>{if(done)return;try{done=true;resolve(b?JSON.parse(b):{})}catch{fail(new Error('Некорректный JSON'))}});req.on('error',fail)})}
function sanitizeName(v){return String(v??'').replace(/[\u0000-\u001f\u007f<>]/g,'').replace(/\s+/g,' ').trim().slice(0,24)}
function freshDB(){return{users:{},sessions:{},rooms:{},botGames:{}}}
function loadDB(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));return d&&d.users?d:freshDB()}catch{return freshDB()}}
let db=loadDB();db.sessions=db.sessions||{};db.rooms=db.rooms||{};db.botGames=db.botGames||{};
for(const u of Object.values(db.users)){u.wins=Number(u.wins||0);u.losses=Number(u.losses||0);u.draws=Number(u.draws||0);u.rating=Number(u.rating||1000);u.inventory=u.inventory||{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'};u.nameHistory=Array.isArray(u.nameHistory)&&u.nameHistory.length?u.nameHistory:[u.name].filter(Boolean);if(!u.dailyGift||typeof u.dailyGift!=='object')u.dailyGift={day:1,lastClaimDate:null};else{u.dailyGift.day=Number(u.dailyGift.day)||1;if(u.dailyGift.day<1||u.dailyGift.day>7)u.dailyGift.day=1;u.dailyGift.lastClaimDate=typeof u.dailyGift.lastClaimDate==='string'?u.dailyGift.lastClaimDate:null}}
function saveDB(){db.rooms=Object.fromEntries(rooms);db.botGames=Object.fromEntries(botGames);const tmp=DB_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function serverDateKey(ts=now()){const d=new Date(ts);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
function serverDateLabel(ts=now()){return new Intl.DateTimeFormat('ru-RU',{timeZone:'UTC',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(ts))}
function dailyGiftState(user,dateKey=serverDateKey()){const dg=user.dailyGift&&typeof user.dailyGift==='object'?user.dailyGift:{};let day=Number(dg.day);if(!Number.isInteger(day)||day<1||day>7)day=1;const lastClaimDate=typeof dg.lastClaimDate==='string'?dg.lastClaimDate:null;const claimedToday=lastClaimDate===dateKey;return{serverDate:dateKey,serverDateLabel:serverDateLabel(),day,reward:DAILY_GIFT_AMOUNTS[day-1],claimedToday,lastClaimDate,nextDay:claimedToday?(day===7?1:day+1):day,nextReward:DAILY_GIFT_AMOUNTS[(claimedToday?(day===7?1:day+1):day)-1]}}
function claimDailyGift(user,dateKey=serverDateKey()){const state=dailyGiftState(user,dateKey);if(state.claimedToday)return{ok:false,error:'Ежедневный подарок уже получен сегодня',state};const reward=state.reward;const nextDay=state.day===7?1:state.day+1;user.dailyGift={day:nextDay,lastClaimDate:dateKey};user.chips=Math.min(MAX_STAKE,user.chips+reward);user.updatedAt=now();return{ok:true,reward,state:{...state,claimedToday:true,nextDay,nextReward:DAILY_GIFT_AMOUNTS[nextDay-1],day:state.day}}}
function getUser(id){return id&&db.users[id]} function uniqueName(name,except=null){const n=sanitizeName(name);if(!n)return'';const used=new Set(Object.values(db.users).filter(u=>u.id!==except).map(u=>u.name.toLowerCase()));return used.has(n.toLowerCase())?'':n}
function ensureUser(name){const n=uniqueName(name);if(!n)throw Error('Никнейм уже занят или некорректен');const u={id:uid(),name:n,nameHistory:[n],chips:100000,inventory:{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'},vip:false,banned:false,wins:0,losses:0,draws:0,rating:1000,createdAt:now(),updatedAt:now(),dailyGift:{day:1,lastClaimDate:null}};db.users[u.id]=u;saveDB();return u}
function userView(u){const inv=JSON.parse(JSON.stringify(u.inventory));const gift=dailyGiftState(u);if(!u.vip){if(inv.selectedBoard==='vip_jewel')inv.selectedBoard='classic';if(inv.selectedPieces==='vip_gem')inv.selectedPieces='classic'}return{id:u.id,name:u.name,nameHistory:Array.isArray(u.nameHistory)?u.nameHistory.slice(-20):[u.name].filter(Boolean),chips:u.chips,inventory:inv,vip:!!u.vip,banned:!!u.banned,wins:u.wins,losses:u.losses,draws:u.draws,rating:u.rating,dailyGift:gift}}
function parseCookies(req){const o={};for(const x of String(req.headers.cookie||'').split(';')){const i=x.indexOf('=');if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())}return o}
function setCookie(res,n,v,max){res.setHeader('Set-Cookie',`${n}=${encodeURIComponent(v)}; Max-Age=${max}; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`)} function clearCookie(res,n){setCookie(res,n,'',0)}
function sessionKey(t){return crypto.createHash('sha256').update(String(t)).digest('hex')}
for(const [k,s] of Object.entries(db.sessions)){if(s?.userId)sessions.set(k,s)}
function persistSession(token,rec){db.sessions[sessionKey(token)]=rec;saveDB()} function dropSession(token){delete db.sessions[sessionKey(token)];sessions.delete(token)}
function currentUser(req,res){const token=parseCookies(req).sani_session,s=sessions.get(token)||db.sessions[sessionKey(token)];if(!s)throw Object.assign(new Error('Сессия не найдена'),{status:401});if(now()-s.createdAt>SESSION_TTL){dropSession(token);clearCookie(res,'sani_session');throw Object.assign(new Error('Сессия истекла'),{status:401})}const u=getUser(s.userId);if(!u||u.banned){dropSession(token);clearCookie(res,'sani_session');throw Object.assign(new Error(u?'Пользователь заблокирован':'Пользователь не найден'),{status:u?403:401})}s.lastSeen=now();return u}
function requireAdmin(req,res){const s=adminSessions.get(parseCookies(req).sani_admin);if(!s||now()-s.createdAt>ADMIN_SESSION_TTL)throw Object.assign(new Error('Доступ запрещён'),{status:401});return true}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim().slice(0,80)}
function allowRate(key,limit,win){const t=now(),a=(rateBuckets.get(key)||[]).filter(x=>t-x<win);if(a.length>=limit){rateBuckets.set(key,a);return false}a.push(t);rateBuckets.set(key,a);return true}
function sameSecret(a,b){const x=Buffer.from(String(a??'')),y=Buffer.from(String(b??''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function cleanupTransient(){const t=now();for(const [k,a] of rateBuckets){const fresh=a.filter(x=>t-x<RATE_WINDOW);if(fresh.length)rateBuckets.set(k,fresh);else rateBuckets.delete(k)}for(const [k,s] of sessions){if(!s?.userId||t-s.createdAt>SESSION_TTL){sessions.delete(k);delete db.sessions[sessionKey(k)]}}for(const [k,s] of adminSessions)if(!s?.createdAt||t-s.createdAt>ADMIN_SESSION_TTL)adminSessions.delete(k);}

// ---- Checkers engine: Russian-style custom SANI rules ----
function xy(s){return[s%8,Math.floor(s/8)]} function at(f,r){return r*8+f} function inside(f,r){return f>=0&&f<8&&r>=0&&r<8} function sideOf(p){return p&&p.toLowerCase()==='w'?'w':p&&p.toLowerCase()==='b'?'b':null} function enemy(c){return c==='w'?'b':'w'}
const DIAG=[[1,1],[1,-1],[-1,1],[-1,-1]];
const START_POS='b1b1b1b1/1b1b1b1b/b1b1b1b1/8/8/1w1w1w1w/w1w1w1w1/1w1w1w1w w';
function parsePos(str){const [placement,side='w']=String(str||START_POS).trim().split(/\s+/),b=Array(64).fill(null);let r=7,f=0;for(const ch of placement){if(ch==='/'){r--;f=0}else if(/[1-8]/.test(ch))f+=+ch;else if(/[wWbB]/.test(ch)){if((f+r)%2===0)throw Error('Шашка должна стоять на тёмной клетке');b[at(f++,r)]=ch}else throw Error('Некорректная позиция')}if(r!==0||f!==8||!['w','b'].includes(side))throw Error('Некорректная позиция');return{board:b,side,captureFrom:null,history:[]}}
function pos(st){let p='';for(let r=7;r>=0;r--){let e=0;for(let f=0;f<8;f++){const x=st.board[at(f,r)];if(!x)e++;else{if(e){p+=e;e=0}p+=x}}if(e)p+=e;if(r)p+='/'}return p+' '+st.side}
function clone(st){return{board:st.board.slice(),side:st.side,captureFrom:st.captureFrom,history:st.history.slice()}}
function captureMovesFor(st,from){const p=st.board[from],c=sideOf(p);if(!p||c!==st.side)return[];const [f,r]=xy(from),out=[];if(p==='w'||p==='b'){for(const[df,dr]of DIAG){const mf=f+df,mr=r+dr,tf=f+2*df,tr=r+2*dr;if(inside(tf,tr)&&inside(mf,mr)){const mid=st.board[at(mf,mr)],to=at(tf,tr);if(mid&&sideOf(mid)===enemy(c)&&!st.board[to])out.push({from,to,capture:at(mf,mr)})}}}else{for(const[df,dr]of DIAG){let F=f+df,R=r+dr,seen=-1;while(inside(F,R)){const s=at(F,R),q=st.board[s];if(q){if(sideOf(q)===c)break;if(seen!==-1)break;seen=s}else if(seen!==-1)out.push({from,to:s,capture:seen});F+=df;R+=dr}}}return out}
function quietMovesFor(st,from){const p=st.board[from],c=sideOf(p);if(!p||c!==st.side)return[];const [f,r]=xy(from),out=[];if(p==='w'||p==='b'){const dr=c==='w'?1:-1;for(const df of[-1,1]){const F=f+df,R=r+dr;if(inside(F,R)&&!st.board[at(F,R)])out.push({from,to:at(F,R)})}}else{for(const[df,dr]of DIAG){let F=f+df,R=r+dr;while(inside(F,R)&&!st.board[at(F,R)]){out.push({from,to:at(F,R)});F+=df;R+=dr}}}return out}
function allCaptures(st){const out=[];for(let i=0;i<64;i++)if(sideOf(st.board[i])===st.side)out.push(...captureMovesFor(st,i));return out}
function allMoves(st){const caps=allCaptures(st);if(caps.length)return caps;const out=[];for(let i=0;i<64;i++)if(sideOf(st.board[i])===st.side)out.push(...quietMovesFor(st,i));return out}
function legalMoves(st){if(st.captureFrom!=null)return captureMovesFor(st,st.captureFrom);return allMoves(st)}
function applyMove(st,m){const n=clone(st),p=n.board[m.from],c=n.side;n.board[m.from]=null;if(m.capture!=null)n.board[m.capture]=null;let q=p;const [,r]=xy(m.to);if(p==='w'&&r===7)q='W';if(p==='b'&&r===0)q='B';n.board[m.to]=q;const more=m.capture!=null?captureMovesFor(n,m.to):[];/* A normal non-capture move ALWAYS ends the turn. Only a capture may keep the turn for a continuation. */if(m.capture!=null&&more.length){n.captureFrom=m.to}else{n.captureFrom=null;n.side=enemy(c)}n.history.push(pos(n));return n}
function parseMove(st,from,to){return legalMoves(st).find(m=>m.from===from&&m.to===to)||null}
function gameStatus(st){const pieces=st.board.filter(Boolean);if(!pieces.some(p=>sideOf(p)==='w'))return'b';if(!pieces.some(p=>sideOf(p)==='b'))return'w';if(!legalMoves(st).length)return enemy(st.side);return null}
function moveRecord(m,st){return{from:m.from,to:m.to,capture:m.capture==null?null:m.capture,piece:st.board[m.from]}}
function createRoom(stake){let id;do{id=String(crypto.randomInt(1000,10000))}while(rooms.has(id));return rooms.set(id,{id,status:'waiting',players:{},createdAt:now(),lastActivity:now(),pos:START_POS,turn:'w',captureFrom:null,result:null,winner:null,drawReason:null,drawOffer:null,lastMove:null,moves:[],chat:[],stake,bank:0,revision:0,paid:false,rematchOffers:{},rematchRoomId:null}).get(id)}
function createRematchRoom(oldRoom){const ps=Object.values(oldRoom.players);if(ps.length!==2)return null;const stake=Math.floor(oldRoom.stake||0);const users=ps.map(p=>getUser(p.accountId));if(users.some(u=>!u||u.banned||u.chips<stake))return null;for(const u of users){u.chips-=stake;u.updatedAt=now()}const r=createRoom(stake);r.status='playing';r.bank=stake*2;r.rematchOf=oldRoom.id;for(const p of ps){const id=uid();r.players[id]={uid:id,name:getUser(p.accountId).name,side:p.side,lastSeen:now(),accountId:p.accountId}}r.lastActivity=now();oldRoom.rematchRoomId=r.id;oldRoom.rematchReady=true;oldRoom.revision++;return r}
function roomState(room){const st=parsePos(room.pos);st.captureFrom=room.captureFrom;return st}
function saveRoomState(room,st){room.pos=pos(st);room.turn=st.side;room.captureFrom=st.captureFrom}
function sanitizeRoom(room,pid){return{id:room.id,status:room.status,turn:room.turn,captureFrom:room.captureFrom,players:Object.values(room.players).map(p=>({uid:p.uid,name:p.name,side:p.side,vip:!!getUser(p.accountId)?.vip,online:now()-p.lastSeen<PLAYER_TIMEOUT,disconnectDeadline:p.disconnectDeadline||null})),position:room.pos,result:room.result,winner:room.winner,drawReason:room.drawReason,drawOffer:room.drawOffer,lastMove:room.lastMove,moves:room.moves||[],revision:room.revision,chat:room.chat.slice(-30),stake:room.stake,bank:room.bank,selfSide:room.players[pid]?.side||null,rematchOffered:!!room.rematchOffers?.[room.players[pid]?.accountId],rematchReady:!!room.rematchRoomId,rematchRoomId:room.rematchRoomId||null,forfeitReason:room.resignPlayer?`Игрок «${room.resignPlayer}» сдался`:room.leavePlayer?`Игрок «${room.leavePlayer}» покинул стол`:room.disconnectPlayer?`Игрок «${room.disconnectPlayer}» не вернулся в течение 1 минуты`:null}}
function settleWinner(room){if(room.paid)return;room.paid=true;const ps=Object.values(room.players),w=ps.find(p=>p.side===room.winner),l=ps.find(p=>p.side!==room.winner);const wu=w&&getUser(w.accountId),lu=l&&getUser(l.accountId);if(wu){wu.chips+=room.bank;wu.wins++;wu.rating+=25;wu.updatedAt=now()}if(lu){lu.losses++;lu.rating=Math.max(0,lu.rating-18);lu.updatedAt=now()}saveDB()}
function settleDraw(room){if(room.paid)return;room.paid=true;for(const p of Object.values(room.players)){const u=getUser(p.accountId);if(u){u.chips+=Math.floor(room.bank/Math.max(1,Object.keys(room.players).length));u.draws++;u.rating+=3;u.updatedAt=now()}}saveDB()}
function settleBot(g,result){if(g.settled)return;g.settled=true;const u=getUser(g.userId);if(u){if(result==='win'){u.chips+=g.stake*2;u.wins++;u.rating+=25}else if(result==='loss'){u.losses++;u.rating=Math.max(0,u.rating-18)}else if(result==='draw'||result==='cancelled'){u.chips+=g.stake;if(result==='draw'){u.draws++;u.rating+=3}}u.updatedAt=now()}saveDB()}
function checkDisconnect(room){if(room.status!=='playing'||room.result)return;const t=now(),ps=Object.values(room.players);for(const p of ps)if(t-p.lastSeen>PLAYER_TIMEOUT&&!p.disconnectDeadline)p.disconnectDeadline=p.lastSeen+DISCONNECT_GRACE;const gone=ps.find(p=>p.disconnectDeadline&&t>=p.disconnectDeadline);if(!gone)return;const opp=ps.find(p=>p.uid!==gone.uid);if(opp){room.winner=opp.side;room.result=opp.side==='w'?'1-0':'0-1';room.status='finished';room.disconnectPlayer=gone.name;settleWinner(room)}else{room.status='finished';room.result='cancelled';settleDraw(room)}room.revision++;saveDB()}
function materialCount(st,c){let men=0,kings=0;for(const p of st.board)if(p&&sideOf(p)===c){if(p===p.toUpperCase())kings++;else men++}return{men,kings,total:men+kings}}
function positionEval(st){
  let score=0;
  for(let i=0;i<64;i++){
    const p=st.board[i]; if(!p) continue;
    const [f,r]=xy(i), c=sideOf(p), king=p===p.toUpperCase();
    const sign=c==='w'?1:-1;
    if(king){
      score+=sign*430;
      const center=8-(Math.abs(f-3.5)+Math.abs(r-3.5))*2;
      score+=sign*center*9;
      const mobility=quietMovesFor(st,i).length+captureMovesFor(st,i).length;
      score+=sign*mobility*5;
    }else{
      score+=sign*100;
      const adv=c==='w'?r:7-r;
      score+=sign*adv*13;
      const center=7-(Math.abs(f-3.5)+Math.abs(r-3.5));
      score+=sign*center*4;
      if((c==='w'&&r===0)||(c==='b'&&r===7)) score+=sign*6;
      if(f===0||f===7) score+=sign*2;
    }
  }
  const w=materialCount(st,'w'), b=materialCount(st,'b');
  score+=(w.kings-b.kings)*34;
  score+=(w.total-b.total)*12;
  const sideMoves=legalMoves(st).length;
  score+=(st.side==='w'?1:-1)*sideMoves*4;
  return score;
}
function aiActions(st){
  /* During a capture sequence legalMoves() is restricted to the same capturing piece.
     There is NO voluntary end action: the turn ends only after that piece has no capture. */
  return legalMoves(st).map(move=>({type:'move',move}));
}
function applyAIAction(st,a){return applyMove(st,a.move)}
function actionKey(a){return `${a.move.from}-${a.move.to}-${a.move.capture==null?'x':a.move.capture}`}
function orderActions(st,actions,ttBest){
  return actions.sort((A,B)=>{
    const ka=actionKey(A),kb=actionKey(B); if(ttBest===ka)return -1;if(ttBest===kb)return 1;
    const va=(A.move.capture!=null?500:0)+((st.board[A.move.from]||'').toUpperCase()===(st.board[A.move.from]||'')?30:0);
    const vb=(B.move.capture!=null?500:0)+((st.board[B.move.from]||'').toUpperCase()===(st.board[B.move.from]||'')?30:0);
    return vb-va;
  });
}
function createAI(level){
  const cfg=BOT_LEVELS[level]||BOT_LEVELS[2],tt=new Map(),nodes={n:0};
  function minimax(x,d,alpha,beta,root,deadline){
    nodes.n++; if((nodes.n&2047)===0&&Date.now()>deadline)throw new Error('AI_TIMEOUT');
    const winner=gameStatus(x); if(winner)return winner===root?10000000+d:-10000000-d;
    if(d<=0)return (root==='w'?1:-1)*positionEval(x);
    const key=pos(x)+'|'+d+'|'+(x.captureFrom==null?'':'c'+x.captureFrom),hit=tt.get(key);
    if(hit&&hit.depth>=d)return hit.value;
    let best=-Infinity;
    const actions=orderActions(x,aiActions(x),hit?.best);
    for(const a of actions){const v=minimax(applyAIAction(x,a),d-1,alpha,beta,root,deadline);if(v>best)best=v;if(best>alpha)alpha=best;if(alpha>=beta)break}
    tt.set(key,{depth:d,value:best,best:actions[0]?actionKey(actions[0]):null});if(tt.size>60000)tt.delete(tt.keys().next().value);return best;
  }
  function choose(st){
    const actions=aiActions(st);if(!actions.length)return null;
    if(cfg.random){
      const captures=actions.filter(a=>a.type==='move'&&a.move.capture!=null), pool=captures.length&&Math.random()<cfg.captureBias?captures:actions;
      return pool[Math.floor(Math.random()*pool.length)];
    }
    const deadline=Date.now()+cfg.timeMs;let best=actions[0],bestScore=-Infinity,lastCompleted=1;
    for(let d=1;d<=cfg.depth;d++){
      try{
        let localBest=best,localScore=-Infinity;
        for(const a of orderActions(st,actions.slice(),null)){
          const v=minimax(applyAIAction(st,a),d-1,-Infinity,Infinity,st.side,deadline);
          if(v>localScore){localScore=v;localBest=a}
        }
        best=localBest;bestScore=localScore;lastCompleted=d;
        if(Math.abs(bestScore)>=9000000)break;
      }catch(e){if(e.message!=='AI_TIMEOUT')throw e;break}
    }
    return best;
  }
  return {choose,stats:()=>({nodes:nodes.n,tt:tt.size,lastDepth:cfg.depth})};
}
const BOT_LEVELS={
  1:{name:'Безразрядник',style:'Интуитивный новичок',description:'Случайный выбор среди допустимых ходов с базовым приоритетом взятий.',depth:1,timeMs:25,random:true,captureBias:.62},
  2:{name:'1-й разряд',style:'Тактический',description:'Уверенный альфа-бета поиск, приоритет взятий, продвижения и активности.',depth:5,timeMs:140,random:false},
  3:{name:'Гроссмейстер',style:'Позиционно-тактический',description:'Глубокий поиск с транспозициями, оценкой материала, темпа, центра и дамок.',depth:8,timeMs:380,random:false}
};
const aiCache=new Map();
function chooseBotAction(st,level){let ai=aiCache.get(level);if(!ai){ai=createAI(level);aiCache.set(level,ai)}return ai.choose(st)}
function chooseBotMove(st,level){const a=chooseBotAction(st,level);return a?.type==='move'?a.move:null}
function advanceBot(g,st){const rec=[];let n=st,result=gameStatus(n),guard=0;while(!result&&n.side==='b'&&guard++<80){const a=chooseBotAction(n,g.level);if(!a)break;const before=n;n=applyAIAction(n,a);if(a.type==='move')rec.push(moveRecord(a.move,before));result=gameStatus(n);if(n.side!=='b')break}return{st:n,rec,result}}
const hintCache=new Map();function chooseHint(st){const key=pos(st)+'|'+(st.captureFrom==null?'':'c'+st.captureFrom),hit=hintCache.get(key);if(hit)return hit;let m=chooseBotMove(st,3);if(!m){const a=createAI(3).choose(st);m=a?.type==='move'?a.move:null}if(!m)return null;const r={from:m.from,to:m.to,move:moveRecord(m,st),reason:m.capture!=null?'Взятие выигрывает шашку.': 'Ход улучшает позицию и активность шашки.',threat:m.capture!=null?'Соперник теряет материал.':'Создаётся давление на диагоналях.'};hintCache.set(key,r);if(hintCache.size>256)hintCache.delete(hintCache.keys().next().value);return r}
function cancelUserGames(userId,reason='Администратор завершил партию'){
  for(const room of rooms.values()){
    const has=Object.values(room.players).some(p=>p.accountId===userId);
    if(!has||room.result)continue;
    room.status='finished';room.result='cancelled';room.drawReason=reason;room.drawOffer=null;room.paid=true;
    const count=Math.max(1,Object.keys(room.players).length);
    for(const p of Object.values(room.players)){const u=getUser(p.accountId);if(u)u.chips+=Math.floor(room.bank/count);}
    room.revision++;room.lastActivity=now();
  }
  for(const g of botGames.values()){
    if(g.userId===userId&&!g.settled){g.status='finished';g.result='cancelled';g.settled=true;const u=getUser(g.userId);if(u)u.chips+=g.stake;g.lastActivity=now();}
  }
}
function adminStats(){
  const users=Object.values(db.users);return{players:users.length,activePlayers:users.filter(u=>!u.banned).length,banned:users.filter(u=>u.banned).length,vip:users.filter(u=>u.vip).length,totalChips:users.reduce((a,u)=>a+Number(u.chips||0),0),waitingRooms:[...rooms.values()].filter(r=>r.status==='waiting').length,playingRooms:[...rooms.values()].filter(r=>r.status==='playing').length,botGames:[...botGames.values()].filter(g=>g.status==='playing'&&!g.settled).length}
}
// load persisted rooms/bots
for(const [id,r] of Object.entries(db.rooms)){if(r?.id&&r?.players&&r?.pos){rooms.set(id,r)}}for(const [id,g] of Object.entries(db.botGames)){if(g?.id&&g?.userId&&g?.position){botGames.set(id,g)}}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true});try{
if(req.method==='POST'&&p==='/api/auth'){if(!allowRate(`auth:${clientIp(req)}`,12,60000))return json(res,429,{ok:false,error:'Слишком много запросов. Попробуйте позже.'});let user;try{user=currentUser(req,res)}catch{}if(user)return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES}});const b=await readBody(req);if(!sanitizeName(b.name))return json(res,200,{ok:true,needsName:true});user=ensureUser(b.name);const token=crypto.randomBytes(32).toString('hex');const rec={userId:user.id,createdAt:now(),lastSeen:now()};sessions.set(token,rec);persistSession(token,rec);setCookie(res,'sani_session',token,SESSION_TTL);return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='POST'&&p==='/api/logout'){const c=parseCookies(req);if(c.sani_session)dropSession(c.sani_session);clearCookie(res,'sani_session');saveDB();return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/state'){const user=currentUser(req,res);return json(res,200,{ok:true,user:userView(user),store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='GET'&&p==='/api/daily-gift'){const user=currentUser(req,res);return json(res,200,{ok:true,...dailyGiftState(user),chips:user.chips})}
if(req.method==='POST'&&p==='/api/daily-gift/claim'){if(!allowRate(`daily-gift:${clientIp(req)}`,10,RATE_WINDOW))return json(res,429,{ok:false,error:'Слишком много запросов к подарку'});const user=currentUser(req,res),result=claimDailyGift(user);if(!result.ok)return json(res,409,{ok:false,error:result.error,...result.state,chips:user.chips});saveDB();return json(res,200,{ok:true,...dailyGiftState(user),reward:result.reward,claimedReward:result.reward,chips:user.chips,user:userView(user)})}
if(req.method==='POST'&&p==='/api/profile/name'){if(!allowRate(`rename:${clientIp(req)}`,10,60000))return json(res,429,{ok:false,error:'Слишком много смен никнейма'});const user=currentUser(req,res),b=await readBody(req),n=uniqueName(b.name,user.id);if(!n)return json(res,400,{ok:false,error:'Никнейм уже занят или некорректен'});if(n===user.name)return json(res,200,{ok:true,user:userView(user)});user.name=n;user.nameHistory=Array.isArray(user.nameHistory)?user.nameHistory.filter(x=>x!==n):[];user.nameHistory.push(n);user.updatedAt=now();for(const r of rooms.values())for(const pl of Object.values(r.players))if(pl.accountId===user.id)pl.name=n;saveDB();return json(res,200,{ok:true,user:userView(user),accountId:user.id,nameHistory:user.nameHistory.slice(-20)})}
if(req.method==='POST'&&p==='/api/shop/buy'){const user=currentUser(req,res),b=await readBody(req),arr=b.type==='board'?STORE_BOARDS:b.type==='pieces'?STORE_PIECES:null,id=String(b.itemId||'');if(!arr)return json(res,400,{ok:false,error:'Неверный тип товара'});const it=arr.find(x=>x[0]===id);if(!it)return json(res,404,{ok:false,error:'Товар не найден'});if(it[4]==='vip')return json(res,403,{ok:false,error:'Этот предмет доступен только VIP-игрокам'});const inv=b.type==='board'?user.inventory.boards:user.inventory.pieces;if(inv.includes(id))return json(res,200,{ok:true,user:userView(user)});if(user.chips<it[3])return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=it[3];inv.push(id);user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/shop/select'){const user=currentUser(req,res),b=await readBody(req),id=String(b.itemId||'');if(id==='vip_jewel'||id==='vip_gem'){if(!user.vip)return json(res,403,{ok:false,error:'Этот предмет доступен только VIP-игрокам'});if(id==='vip_jewel')user.inventory.selectedBoard=id;else user.inventory.selectedPieces=id}else if(b.type==='board'&&user.inventory.boards.includes(id))user.inventory.selectedBoard=id;else if(b.type==='pieces'&&user.inventory.pieces.includes(id))user.inventory.selectedPieces=id;else return json(res,400,{ok:false,error:'Предмет не куплен'});user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/admin/login'){if(!ADMIN_PASSWORD)return json(res,503,{ok:false,error:'ADMIN_PASSWORD не настроен'});if(!allowRate(`admin:${clientIp(req)}`,5,60000))return json(res,429,{ok:false,error:'Слишком много попыток входа'});const b=await readBody(req);if(!sameSecret(b.password,ADMIN_PASSWORD))return json(res,401,{ok:false});const t=crypto.randomBytes(32).toString('hex');adminSessions.set(t,{createdAt:now()});setCookie(res,'sani_admin',t,ADMIN_SESSION_TTL);return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/admin/logout'){adminSessions.delete(parseCookies(req).sani_admin);clearCookie(res,'sani_admin');return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/admin/players'){requireAdmin(req,res);const q=sanitizeName(u.searchParams.get('q')||'').toLowerCase();let players=Object.values(db.users);if(q)players=players.filter(x=>x.name.toLowerCase().includes(q)||x.id.toLowerCase().includes(q));return json(res,200,{ok:true,stats:adminStats(),players:players.map(userView)})}
if(req.method==='GET'&&p==='/api/admin/stats'){requireAdmin(req,res);return json(res,200,{ok:true,stats:adminStats()})}
if(req.method==='POST'&&p==='/api/admin/action'){requireAdmin(req,res);if(!allowRate(`admin-action:${clientIp(req)}`,60,RATE_WINDOW))return json(res,429,{ok:false,error:'Слишком много административных операций'});const b=await readBody(req);if(b.action==='clear_database'){rooms.clear();botGames.clear();sessions.clear();db=freshDB();saveDB();return json(res,200,{ok:true})}const user=getUser(b.userId);if(!user)return json(res,404,{ok:false,error:'Игрок не найден'});if(b.action==='chips'){const n=Number(b.amount);if(!Number.isFinite(n))return json(res,400,{ok:false,error:'Некорректная сумма'});user.chips=Math.min(MAX_STAKE,Math.max(0,Math.floor(user.chips+n)))}else if(b.action==='set_chips'){const n=Number(b.amount);if(!Number.isFinite(n)||n<0||n>1e9)return json(res,400,{ok:false,error:'Некорректное количество фишек'});user.chips=Math.floor(n)}else if(b.action==='vip')user.vip=!!b.value;else if(b.action==='ban'){user.banned=!!b.value;if(user.banned){for(const [t,s] of sessions)if(s.userId===user.id){sessions.delete(t);delete db.sessions[sessionKey(t)]}cancelUserGames(user.id,'Игрок заблокирован администратором')}}else if(b.action==='rename'){const n=uniqueName(b.name,user.id);if(!n)return json(res,400,{ok:false,error:'Никнейм уже занят'});user.name=n;user.nameHistory=Array.isArray(user.nameHistory)?user.nameHistory.filter(x=>x!==n):[];user.nameHistory.push(n);for(const r of rooms.values())for(const pl of Object.values(r.players))if(pl.accountId===user.id)pl.name=n}else if(b.action==='delete'){cancelUserGames(user.id,'Аккаунт удалён администратором');delete db.users[user.id];for(const [t,s] of sessions)if(s.userId===user.id){sessions.delete(t);delete db.sessions[sessionKey(t)]}}else return json(res,400,{ok:false,error:'Неизвестное действие'});if(db.users[user.id])user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:db.users[user.id]?userView(user):null,stats:adminStats()})}
if(req.method==='GET'&&p==='/api/leaderboard'){const players=Object.values(db.users).sort((a,b)=>b.wins-a.wins||b.rating-a.rating||b.chips-a.chips).slice(0,50).map(u=>({name:u.name,chips:u.chips,vip:!!u.vip,wins:u.wins,losses:u.losses,draws:u.draws,rating:u.rating}));return json(res,200,{ok:true,players})}
if(req.method==='POST'&&p==='/api/bot/start'){if(!allowRate(`bot-start:${clientIp(req)}`,10,60000))return json(res,429,{ok:false,error:'Слишком много запусков бота'});const user=currentUser(req,res),b=await readBody(req),stake=Math.min(MAX_STAKE,Math.max(0,Math.floor(Number(b.stake)||0))),level=Math.min(3,Math.max(1,Math.floor(Number(b.level)||2)));if(stake>user.chips)return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=stake;const id=uid();botGames.set(id,{id,userId:user.id,stake,level,createdAt:now(),lastActivity:now(),settled:false,status:'playing',position:START_POS,turn:'w',captureFrom:null,lastMove:null,moves:[]});user.updatedAt=now();saveDB();return json(res,200,{ok:true,gameId:id,level,levelName:(BOT_LEVELS[level]||BOT_LEVELS[2]).name,levelStyle:(BOT_LEVELS[level]||BOT_LEVELS[2]).style,stake,user:userView(user),position:START_POS,result:null})}
if(req.method==='GET'&&p==='/api/bot/state'){const user=currentUser(req,res),g=botGames.get(String(u.searchParams.get('gameId')||''));if(!g||g.userId!==user.id)return json(res,404,{ok:false,error:'Партия бота не найдена'});return json(res,200,{ok:true,gameId:g.id,level:g.level,levelName:(BOT_LEVELS[g.level]||BOT_LEVELS[2]).name,levelStyle:(BOT_LEVELS[g.level]||BOT_LEVELS[2]).style,stake:g.stake,position:g.position,captureFrom:g.captureFrom,result:g.result||null,status:g.status,moves:g.moves||[],user:userView(user)})}
if(req.method==='POST'&&p==='/api/bot/resign'){const user=currentUser(req,res),b=await readBody(req),g=botGames.get(String(b.gameId||''));if(!g||g.userId!==user.id||g.settled)return json(res,400,{ok:false,error:'Партия бота не найдена'});if(g.status!=='playing')return json(res,400,{ok:false,error:'Партия завершена'});g.status='finished';g.result='loss';g.lastActivity=now();settleBot(g,'loss');return json(res,200,{ok:true,result:'loss',user:userView(user)})}
if(req.method==='POST'&&p==='/api/bot/move'){const user=currentUser(req,res),b=await readBody(req),g=botGames.get(String(b.gameId||''));if(!g||g.userId!==user.id||g.settled)return json(res,400,{ok:false,error:'Партия бота не найдена'});if(g.status!=='playing')return json(res,400,{ok:false,error:'Партия завершена'});const st=parsePos(g.position);st.captureFrom=g.captureFrom;if(st.side!=='w')return json(res,400,{ok:false,error:'Сейчас ход бота'});const mv=parseMove(st,Number(b.from),Number(b.to));if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});let n=applyMove(st,mv);const rec=[moveRecord(mv,st)];let result=gameStatus(n);if(!result&&n.side==='b'){const adv=advanceBot(g,n);n=adv.st;rec.push(...adv.rec);result=adv.result}g.position=pos(n);g.turn=n.side;g.captureFrom=n.captureFrom;g.lastMove=rec[rec.length-1];g.moves=(g.moves||[]).concat(rec).slice(-500);g.lastActivity=now();if(result){g.status='finished';g.result=result==='w'?'win':'loss';settleBot(g,g.result==='win'?'win':'loss')}saveDB();return json(res,200,{ok:true,position:g.position,captureFrom:g.captureFrom,result:g.result||null,moves:rec,user:userView(user)})}
if(req.method==='POST'&&p==='/api/hint'){if(!allowRate(`hint:${clientIp(req)}`,12,60000))return json(res,429,{ok:false,error:'Подсказки временно ограничены'});const user=currentUser(req,res);if(!user.vip)return json(res,403,{ok:false,error:'Подсказка доступна только VIP'});const b=await readBody(req),st=parsePos(String(b.position||START_POS));st.captureFrom=b.captureFrom==null?null:Number(b.captureFrom);const h=chooseHint(st);return json(res,200,{ok:true,available:!!h,...(h||{})})}
if(req.method==='POST'&&p==='/api/room/create'){const user=currentUser(req,res),b=await readBody(req),stake=Math.min(MAX_STAKE,Math.max(0,Math.floor(Number(b.stake)||0)));if(!allowRate(`create:${clientIp(req)}`,10,60000))return json(res,429,{ok:false,error:'Слишком много столов'});if(user.chips<stake)return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=stake;const room=createRoom(stake),id=uid();room.players[id]={uid:id,name:user.name,side:'w',lastSeen:now(),accountId:user.id};room.bank=stake;saveDB();return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'w',user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/join'){if(!allowRate(`join:${clientIp(req)}`,20,60000))return json(res,429,{ok:false,error:'Слишком много попыток входа в стол'});const user=currentUser(req,res),b=await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase());if(!room)return json(res,404,{ok:false,error:'Комната не найдена'});if(room.status!=='waiting'||Object.keys(room.players).length>=2)return json(res,400,{ok:false,error:'Комната недоступна'});if(user.chips<room.stake)return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=room.stake;const id=uid();room.players[id]={uid:id,name:user.name,side:'b',lastSeen:now(),accountId:user.id};room.bank+=room.stake;room.status='playing';room.lastActivity=now();saveDB();return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'b',user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/rematch'){const user=currentUser(req,res);if(!allowRate(`rematch:${user.id}`,12,60000))return json(res,429,{ok:false,error:'Слишком много запросов на реванш'});const b=await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase());if(!room||room.status!=='finished'||room.result==null)return json(res,400,{ok:false,error:'Реванш доступен только после завершения партии'});const player=Object.values(room.players).find(x=>x.accountId===user.id);if(!player)return json(res,404,{ok:false,error:'Игрок не найден за этим столом'});room.rematchOffers=room.rematchOffers||{};room.rematchOffers[user.id]=true;room.lastActivity=now();if(room.rematchRoomId){const nr=rooms.get(room.rematchRoomId),np=Object.values(nr?.players||{}).find(x=>x.accountId===user.id);if(nr&&np)return json(res,200,{ok:true,ready:true,room:sanitizeRoom(nr,np.uid),uid:np.uid,self:np.side,user:userView(user)})}const accepted=Object.keys(room.rematchOffers).length===2;if(accepted){const nr=createRematchRoom(room);if(!nr)return json(res,400,{ok:false,error:'Оба игрока должны иметь достаточно фишек для реванша'});const np=Object.values(nr.players).find(x=>x.accountId===user.id);saveDB();return json(res,200,{ok:true,ready:true,room:sanitizeRoom(nr,np.uid),uid:np.uid,self:np.side,user:userView(user)})}room.revision++;saveDB();return json(res,200,{ok:true,ready:false,room:sanitizeRoom(room,player.uid),user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/rematch-connect'){const user=currentUser(req,res),b=await readBody(req),old=rooms.get(String(b.roomId||'').toUpperCase());if(!old?.rematchRoomId)return json(res,404,{ok:false,error:'Реванш ещё не создан'});const room=rooms.get(old.rematchRoomId),player=Object.values(room?.players||{}).find(x=>x.accountId===user.id);if(!room||!player)return json(res,404,{ok:false,error:'Реванш недоступен'});player.lastSeen=now();player.disconnectDeadline=null;room.lastActivity=now();saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,player.uid),uid:player.uid,self:player.side,user:userView(user)})}
const rm=/^\/api\/room\/(sync|heartbeat|reconnect|move|leave|chat|draw|draw-response|resign)$/.exec(p);if(rm){const user=currentUser(req,res),b=req.method==='GET'?Object.fromEntries(u.searchParams.entries()):await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase()),player=room?.players?.[b.uid];if(!room||!player||player.accountId!==user.id)return json(res,404,{ok:false,error:'Сессия стола не найдена'});player.lastSeen=now();player.disconnectDeadline=null;room.lastActivity=now();checkDisconnect(room);if(rm[1]==='sync'||rm[1]==='heartbeat'||rm[1]==='reconnect')return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side});if(rm[1]==='chat'){if(!allowRate(`chat:${user.id}`,20,RATE_WINDOW))return json(res,429,{ok:false,error:'Слишком много сообщений'});const text=sanitizeName(b.text).slice(0,160);if(text){room.chat.push({uid:user.id,name:user.name,text,ts:now()});room.revision++;room.lastActivity=now();}saveDB();return json(res,200,{ok:true})}if(rm[1]==='leave'){if(room.result)return json(res,400,{ok:false,error:'Игра уже завершена'});room.drawOffer=null;if(room.status==='waiting'){room.leavePlayer=player.name;room.status='finished';room.result='cancelled';settleDraw(room)}else{const opp=Object.values(room.players).find(p=>p.uid!==player.uid);if(opp){room.winner=opp.side;room.result=opp.side==='w'?'1-0':'0-1';room.status='finished';room.leavePlayer=player.name;settleWinner(room)}else{room.status='finished';room.result='cancelled';settleDraw(room)}}room.revision++;room.lastActivity=now();saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
if(rm[1]==='draw'){if(room.status!=='playing')return json(res,400,{ok:false,error:'Игра завершена'});room.drawOffer=player.side;room.revision++;saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
if(rm[1]==='draw-response'){if(!room.drawOffer)return json(res,400,{ok:false,error:'Нет активного предложения ничьей'});if(room.drawOffer===player.side)return json(res,400,{ok:false,error:'Нельзя отвечать на своё предложение'});if(b.accept){room.status='finished';room.result='1/2-1/2';room.drawReason='Соглашение игроков';room.drawOffer=null;settleDraw(room)}else room.drawOffer=null;room.revision++;saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
if(rm[1]==='resign'){if(room.status!=='playing')return json(res,400,{ok:false,error:'Игра завершена'});const opp=Object.values(room.players).find(p=>p.uid!==player.uid);if(opp){room.winner=opp.side;room.result=opp.side==='w'?'1-0':'0-1';room.status='finished';room.resignPlayer=player.name;settleWinner(room)}room.revision++;saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
if(rm[1]==='move'){if(!allowRate(`move:${user.id}`,120,10000))return json(res,429,{ok:false,error:'Слишком много ходов'});if(room.status!=='playing')return json(res,400,{ok:false,error:'Игра завершена'});if(room.turn!==player.side)return json(res,400,{ok:false,error:'Сейчас ход соперника'});const st=roomState(room),mv=parseMove(st,Number(b.from),Number(b.to));if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});const n=applyMove(st,mv);saveRoomState(room,n);room.drawOffer=null;room.lastMove=moveRecord(mv,st);room.moves.push(room.lastMove);room.moves=room.moves.slice(-500);room.revision++;room.lastActivity=now();const result=gameStatus(n);if(result){room.status='finished';room.result=result==='w'?'1-0':'0-1';room.winner=result;settleWinner(room)}else saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}}
}catch(e){return json(res,e.status||400,{ok:false,error:e.message||'Ошибка сервера'})}
if(req.method==='GET'){let fp=path.normalize(path.join(ROOT,p==='/'?'/index.html':p));if(fp!==ROOT&&!fp.startsWith(ROOT+path.sep)||!fs.existsSync(fp))return json(res,404,{error:'not found'});const ext=path.extname(fp),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.mp3':'audio/mpeg','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(fp).pipe(res);return}return json(res,404,{error:'not found'})}
if(require.main===module){setInterval(()=>{cleanupTransient();for(const r of rooms.values()){checkDisconnect(r);if(r.status==='waiting'&&now()-r.createdAt>ROOM_TTL){r.status='finished';r.result='cancelled';settleDraw(r)}if(r.status==='playing'&&now()-r.lastActivity>ROOM_TTL){r.status='finished';r.result='cancelled';settleDraw(r)}}for(const g of botGames.values())if(!g.settled&&now()-g.lastActivity>ROOM_TTL){g.status='finished';g.result='cancelled';settleBot(g,'cancelled')}},1000);http.createServer(route).listen(PORT,'0.0.0.0',()=>console.log(`SANI CHECKERS server: http://localhost:${PORT}`))}
module.exports={parsePos,pos,legalMoves,allCaptures,applyMove,gameStatus,START_POS,chooseBotMove,chooseBotAction,BOT_LEVELS,positionEval,aiActions,applyAIAction,DAILY_GIFT_AMOUNTS,serverDateKey,dailyGiftState,claimDailyGift};
